.PHONY: crawl
crawl:
	go run ./cmd/app --agentsfile=./internal/data/agents.json --seedfile=./internal/data/seed.txt --routines=100 --maxIdleSeconds=1000 --domainsblacklist=./internal/data/blacklist.txt
